version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Building the project...
      - npm run build
      
  build:
    commands:
      - echo Building the project...
      - npm run build
  
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
  discard-paths: no